# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev227+gf87c837.d20251017'
__version_tuple__ = version_tuple = (0, 1, 'dev227', 'gf87c837.d20251017')
